[package]
name = "ex_ore_rs"
version = "0.0.0-git"
authors = []
edition = "2018"

[lib]
name = "ex_ore_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
ore-rs = "0.4.0"
